services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/taskdb
    command: nodemon src/index.ts
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
